In [1]:
!pip install numpy

In [ ]:
import numpy as np 
arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape)     ##

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [5]:
import numpy as np 
arr2 = np.array([1,2,3,4])
arr2.reshape(1,4) #it means 1 row and 5 columns


array([[1, 2, 3, 4]])

In [6]:
arr3 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
arr3.shape

(2, 5)

In [ ]:
np.arange(0,10,2)   ## start , end , step
np.arange(0,10,2).reshape(5,1) # 5 row and 1 column

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4)) ## it creates a an array of 1's with 3 row and 4 columns
np.zeros((4,4)) ## it creates a an array of 0's with 4 row and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
## identity matrix
np.eye(4) # of ordr 4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
import numpy as np 
##attributes of numpy
arr = np.array([[1,2,3],[4,5,3]])
print(arr)
print("SHAPE",arr.shape)
print("dimension of array",arr.ndim)
print("size (number of elemnts)",arr.size)
print("data type",arr.dtype)
print("item size (in bytes)",arr.itemsize)

[[1 2 3]
 [4 5 3]]
SHAPE (2, 3)
dimension of array 2
size (number of elemnts) 6
data type int64
item size (in bytes) 8


## Numpy vectorized Operation

In [18]:
arr1  = np.array([1,2,3,4,5])
arr2  = np.array([10,20,30,40,50])
## element wise addition
print("additon of arr1 and arr2  is",arr1+arr2)
print("subtraction of arr1 and arr2  is",arr1-arr2)
print("multiplication of arr1 and arr2  is",arr1 * arr2)

additon of arr1 and arr2  is [11 22 33 44 55]
subtraction of arr1 and arr2  is [ -9 -18 -27 -36 -45]
multiplication of arr1 and arr2  is [ 10  40  90 160 250]


In [ ]:
## inbuilt functions in numpy
print(np.sqrt(arr1))
print(np.exp(arr1))
print(np.log(arr1))
print(np.sin(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


## +Universal FUnctions

In [47]:
## array slicing and indexing
arr = np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]])
print(arr)
print(arr[1][3])
print(arr[2][2])
print(arr[0][0])
arr[1:,2:]
arr[0:2,0:3]
print(arr[0:2,2:])
arr[1:,1:3]

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]
7
10
1
[[3 4]
 [6 7]]


array([[ 5,  6],
       [ 9, 10]])

In [ ]:
## MODIFY ELEMNTS
arr[0][0] = 100
print(arr)

[[100 100   3   4]
 [  4   5   6   7]
 [  8   9  10  11]]


In [53]:
arr[1:2] = 10
print(arr)

[[ 100  100    3    4]
 [  10   10   10   10]
 [1000 1000 1000 1000]]


In [ ]:
## stat concept --- Normalisation is to change the data in such a way so that your mean is zero and standard deviation is 1 
data  = np.array([1,2,3,4,5,6,7,8,9,10])
mean = np.mean(data)
std = np.std(data)
print(std)
print(mean)
noraml_data = (data - mean)/std
print("NOrmalised datais",noraml_data)

2.8722813232690143
5.5
NOrmalised datais [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


In [ ]:
## logical operations
data  = np.array([1,2,3,4,5,6,7,8,9,10])
data>5
data[data>5]
data[(data>4) & (data <8) ] ## logical and &


array([5, 6, 7])

## Pandas frame work

In [62]:
!pip install pandas

In [ ]:
import pandas as pd


In [65]:
##SERIES
data = [1,2,3,4,5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [67]:
dict = {"a":1,"b":2,"c":3}
seri_dict = pd.Series(dict)
print(seri_dict) ## here index goes from a to c like in earlier case it was from indexes(defualt)

a    1
b    2
c    3
dtype: int64


In [69]:
data  = [10,20,30]
ind = ["a","b","c"]
pd.Series(data,index = ind)

a    10
b    20
c    30
dtype: int64

In [70]:
## DATAFRAME
## create a data frame from a dictionary of list
data = {
    "name":["abhi","yash","tushar"],
    "age":[22,21,22],
    "city":["saharanpur","delhi","mzn"]
}
new_dt = pd.DataFrame(data)
print(new_dt)


     name  age        city
0    abhi   22  saharanpur
1    yash   21       delhi
2  tushar   22         mzn


In [71]:
## create a data frame from a lsit of dictionary
dat_dict = [{"A":1,"B":2},{"C":4,"D":5}]
pd.DataFrame(dat_dict)


,A,B,C,D
0,1.0,2.0,NaN,NaN
1,NaN,NaN,4.0,5.0


In [84]:
df = pd.read_csv("Details.csv")
df.head(5)


,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card


In [85]:
df.tail(8)

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
1492,B-25798,2830,-1981,13,Furniture,Bookcases,EMI
1493,B-25873,7,1,1,Clothing,Hankerchief,COD
1494,B-25740,7,0,2,Clothing,Skirt,COD
1495,B-25700,7,-3,2,Clothing,Hankerchief,COD
1496,B-25757,3151,-35,7,Clothing,Trousers,EMI
1497,B-25973,4141,1698,13,Electronics,Printers,COD
1498,B-25698,7,-2,1,Clothing,Hankerchief,COD
1499,B-25993,4363,305,5,Furniture,Tables,EMI


In [ ]:
## accesing data from dataframe

In [90]:
dat_dict = [{"A":1,"B":2},{"C":4,"D":5}]
df = pd.DataFrame(dat_dict)
df['A']

0    1.0
1    NaN
Name: A, dtype: float64

In [100]:
people = [
    {"Name": "Amit", "Age": 25, "City": "Mumbai"},
    {"Name": "Priya", "Age": 30, "City": "Delhi"},
    {"Name": "Raj", "Age": 22, "City": "Bangalore"},
    {"Name": "Sneha", "Age": 28, "City": "Pune"},
    {"Name": "Vikram", "Age": 35, "City": "Chennai"}
]
df = pd.DataFrame(people)
df 


,Name,Age,City
0,Amit,25,Mumbai
1,Priya,30,Delhi
2,Raj,22,Bangalore
3,Sneha,28,Pune
4,Vikram,35,Chennai


In [101]:
df["Name"] ## this selects the column named "name"

0      Amit
1     Priya
2       Raj
3     Sneha
4    Vikram
Name: Name, dtype: object

In [ ]:
df.loc[0] ## selects the the row wtih index zero ere details of amit

In [ ]:
df.loc[0][1] 

C:\Users\Abhishek Goswami\AppData\Local\Temp\ipykernel_8808\1642692815.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][1] ## selects the the row wtih index zero ere details of amit


np.int64(25)

In [107]:
df.iloc[0][1]

C:\Users\Abhishek Goswami\AppData\Local\Temp\ipykernel_8808\2309508539.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][1]


np.int64(25)

In [108]:
# accssing a specific element
df

,Name,Age,City
0,Amit,25,Mumbai
1,Priya,30,Delhi
2,Raj,22,Bangalore
3,Sneha,28,Pune
4,Vikram,35,Chennai


In [114]:
print(df.at[2,"Age"])
print(df.at[1,"Age"])
print(df.at[0,"Name"])
print(df.at[4,"City"])

22
30
Amit
Chennai


In [ ]:
### data manupilation with Dataframes
##adding column
df["Salary"] = [10000,20000,30000,400000,5000000]
df

,Name,Age,City,Salary
0,Amit,25,Mumbai,10000
1,Priya,30,Delhi,20000
2,Raj,22,Bangalore,30000
3,Sneha,28,Pune,400000
4,Vikram,35,Chennai,5000000


In [124]:
## remove the column
df.drop("Salary",axis=1,inplace=True) ## to remove salary permanently we use inplace = true and axis is to tell rows (0) or column(1)

In [125]:
df

,Name,Age,City
0,Amit,25,Mumbai
1,Priya,30,Delhi
2,Raj,22,Bangalore
3,Sneha,28,Pune
4,Vikram,35,Chennai


In [130]:
df["Age"] = df["Age"]+1


In [131]:
df

,Name,Age,City
0,Amit,26,Mumbai
1,Priya,31,Delhi
2,Raj,23,Bangalore
3,Sneha,29,Pune
4,Vikram,36,Chennai


In [ ]:
df.drop(0) ## it removed the 0th row again not a permanent operation

,Name,Age,City
1,Priya,31,Delhi
2,Raj,23,Bangalore
3,Sneha,29,Pune
4,Vikram,36,Chennai


In [136]:
df.drop(0,inplace=True)